Repository redis-performance/redisbench-admin, pull requests merged in 2021-06, with the labels that each got.

#113 Fixes related to redis-benchmark config
  pyproject.toml
  redisbench_admin/run/redis_benchmark/redis_benchmark.py
  tests/test_data/redis-benchmark2.yml
  tests/test_redis_benchmark.py
Labels: bug

#114 Enabled running ycsb on remote setups
  pyproject.toml
  redisbench_admin/run/common.py
  redisbench_admin/run/ycsb/ycsb.py
  redisbench_admin/run_remote/run_remote.py
  redisbench_admin/utils/redisgraph_benchmark_go.py
  redisbench_admin/utils/results.py
Labels: enhancement, ycsb

#117 Fixed metrics extraction on timeseries exporter in case of missing metrics
  pyproject.toml
  redisbench_admin/utils/remote.py
Labels: bug

#119 Enable CI testing on ubuntu-latest and macOS-latest
  .github/workflows/poetry-ci-test-lint.yml
Labels: enhancement

#120 Updated developer steps. included license updates
  LICENSE
  README.md
  redisbench_admin/__init__.py
  redisbench_admin/cli.py
  redisbench_admin/export/__init__.py
  redisbench_admin/export/args.py
  redisbench_admin/export/common/__init__.py
  redisbench_admin/export/common/common.py
  redisbench_admin/export/export.py
  redisbench_admin/export/memtier_benchmark/__init__.py
  redisbench_admin/export/memtier_benchmark/memtier_benchmark_json_format.py
  redisbench_admin/export/redis_benchmark/__init__.py
  redisbench_admin/export/redis_benchmark/metrics_definition.py
  redisbench_admin/export/redis_benchmark/redis_benchmark_csv_format.py
  redisbench_admin/extract/__init__.py
  redisbench_admin/extract/args.py
  redisbench_admin/extract/extract.py
  redisbench_admin/run/__init__.py
  redisbench_admin/run/args.py
  redisbench_admin/run/common.py
  redisbench_admin/run/redis_benchmark/__init__.py
  redisbench_admin/run/redis_benchmark/redis_benchmark.py
  redisbench_admin/run/redisgraph_benchmark_go/__init__.py
  redisbench_admin/run/redisgraph_benchmark_go/redisgraph_benchmark_go.py
  redisbench_admin/run/run.py
  redisbench_admin/run/tsbs_run_queries_redistimeseries/__init__.py
  redisbench_admin/run/tsbs_run_queries_redistimeseries/tsbs_run_queries_redistimeseries.py
  redisbench_admin/run_local/__init__.py
  redisbench_admin/run_local/args.py
  redisbench_admin/run_local/run_local.py
  redisbench_admin/run_remote/__init__.py
  redisbench_admin/run_remote/args.py
  redisbench_admin/run_remote/run_remote.py
  redisbench_admin/utils/__init__.py
  redisbench_admin/utils/benchmark_config.py
  redisbench_admin/utils/local.py
  redisbench_admin/utils/redisearch.py
  redisbench_admin/utils/redisgraph_benchmark_go.py
  redisbench_admin/utils/remote.py
  redisbench_admin/utils/results.py
  redisbench_admin/utils/utils.py
Labels: maintenance

#121 Finding on-cpu performance hotspots by attaching profiling tools/probers: support for perf (a.k.a. perf_events) record + flame graphs
  poetry.lock
  pyproject.toml
  redisbench_admin/profilers/__init__.py
  redisbench_admin/profilers/flamegraph.pl
  redisbench_admin/profilers/perf.py
  redisbench_admin/profilers/profilers.py
  redisbench_admin/profilers/stackcollapse-perf.pl
  redisbench_admin/run_local/args.py
  redisbench_admin/run_local/run_local.py
Labels: enhancement, perf:record

#124 Added Top entries in text form; added Output graph image in PNG format
  pyproject.toml
  redisbench_admin/profilers/perf.py
  redisbench_admin/profilers/pprof.py
  redisbench_admin/run_local/run_local.py
Labels: profile

#125 run initialization commands before benchmark starts
  redisbench_admin/run_local/run_local.py
Labels: enhancement

#127 Included track of benchmark duration. Small refactor/reuse of code within break/by timeseries
  pyproject.toml
  redisbench_admin/cli.py
  redisbench_admin/profilers/perf.py
  redisbench_admin/profilers/profilers.py
  redisbench_admin/run_local/args.py
  redisbench_admin/run_local/run_local.py
  redisbench_admin/run_remote/args.py
  redisbench_admin/run_remote/run_remote.py
  redisbench_admin/utils/remote.py
  redisbench_admin/utils/utils.py
  tests/test_run_remote.py
Labels: enhancement

#131 Added watchdog feature to keep track of current aws bench VMs. Enabled tracking rdb load time
  poetry.lock
  pyproject.toml
  redisbench_admin/cli.py
  redisbench_admin/compare/__init__.py
  redisbench_admin/export/common/common.py
  redisbench_admin/profilers/perf.py
  redisbench_admin/run/common.py
  redisbench_admin/run_local/run_local.py
  redisbench_admin/run_remote/args.py
  redisbench_admin/run_remote/run_remote.py
  redisbench_admin/utils/local.py
  redisbench_admin/utils/remote.py
  redisbench_admin/utils/utils.py
  redisbench_admin/watchdog/__init__.py
  redisbench_admin/watchdog/args.py
  redisbench_admin/watchdog/watchdog.py
Labels: enhancement

#132 Added by.branch time-series for benchmark_duration and dataset_load_duration metrics
  pyproject.toml
  redisbench_admin/run_remote/run_remote.py
Labels: enhancement

#133 Fixed benchmark repetitions range
  pyproject.toml
  redisbench_admin/run_remote/run_remote.py
Labels: bug

#134 [fix] Fixed standardized metrics by branch
  pyproject.toml
  redisbench_admin/run_remote/run_remote.py
Labels: bug

#135 Enabled Enabled specifying dataset_load_timeout_secs property.
  pyproject.toml
  redisbench_admin/cli.py
  redisbench_admin/run_local/run_local.py
  redisbench_admin/run_remote/args.py
  redisbench_admin/run_remote/run_remote.py
  redisbench_admin/utils/benchmark_config.py
  redisbench_admin/utils/utils.py
  redisbench_admin/watchdog/watchdog.py
  tests/test_benchmark_config.py
  tests/test_data/redisgraph-benchmark-go-dataset-timeout.yml
Labels: enhancement

#136 Fixed redistimeseries_* args for run-remote and watchdog
  redisbench_admin/run_remote/args.py
  redisbench_admin/watchdog/args.py
Labels: bug

#138 [fix] fixed redistimeseries_* args
  pyproject.toml
  redisbench_admin/run_remote/run_remote.py
Labels: bug

#140 Enabled perf-report artifact on PROFILE=1. Fixes dwarf usage and pprof
  pyproject.toml
  redisbench_admin/profilers/perf.py
Labels: bug

#141 Enabled uploading profile results to s3. making txt profile outputs to be main thread related
  pyproject.toml
  redisbench_admin/profilers/perf.py
  redisbench_admin/run_local/args.py
  redisbench_admin/run_local/run_local.py
  redisbench_admin/run_remote/run_remote.py
  redisbench_admin/utils/utils.py
Labels: enhancement

#143 Improved profile reporting table
  redisbench_admin/run_local/run_local.py
  redisbench_admin/run_remote/run_remote.py
  redisbench_admin/utils/remote.py
  redisbench_admin/utils/utils.py
  redisbench_admin/watchdog/watchdog.py
Labels: enhancement

#144 Bumping version from 0.2.11 to 0.2.12
  pyproject.toml
Labels: skip-changelog

#149 [add] Enabled logfile on remote setups. Fetching remote logfile in case of errors
  pyproject.toml
  redisbench_admin/run_remote/run_remote.py
  redisbench_admin/utils/redisgraph_benchmark_go.py
Labels: enhancement

#150 Fix: remote results file should not be the same across variations
  redisbench_admin/run_remote/run_remote.py
Labels: bug

#152 Further improved compare mode to focus on regressions only
  pyproject.toml
  redisbench_admin/compare/args.py
  redisbench_admin/compare/compare.py
Labels: enhancement

#153 Kickoff of oss-cluster benchmarks and local runs
  pyproject.toml
  redisbench_admin/environments/__init__.py
  redisbench_admin/environments/oss_cluster.py
  redisbench_admin/environments/oss_standalone.py
  redisbench_admin/profilers/perf.py
  redisbench_admin/profilers/profilers.py
  redisbench_admin/profilers/vtune.py
  redisbench_admin/run/common.py
  redisbench_admin/run/tsbs_run_queries_redistimeseries/tsbs_run_queries_redistimeseries.py
  redisbench_admin/run_local/args.py
  redisbench_admin/run_local/run_local.py
  redisbench_admin/run_remote/run_remote.py
  redisbench_admin/utils/benchmark_config.py
  redisbench_admin/utils/local.py
  tests/test_common.py
  tests/test_data/common-properties-v0.3.yml
  tests/test_data/tsbs-devops-ingestion-scale100-4days-v2.yml
  tests/test_local.py
  tests/test_remote.py
  tests/test_run_remote.py
Labels: enhancement, profile

#154 WIP on oss-cluster benchmarks and local runs: enable specify max number of profilers
  redisbench_admin/environments/oss_cluster.py
  redisbench_admin/run_local/args.py
  redisbench_admin/run_local/run_local.py
  redisbench_admin/utils/local.py
Labels: enhancement
